/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp->x + argp->y;

    // operandos ops;
    // int *result;
    // ops.x = x;
    // ops.y = y;
    // /* Chama o stub cliente criado pelo rpcgen */
    // result = add_100(&ops,clnt);
    // if (result==NULL) {
    //     fprintf(stderr,"Problema na chamada RPC\n");
    //     exit(0);
    // }

	return &result;
}

int *
sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp->x - argp->y;

	return &result;
}
