// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: src/operandos/operandos.proto

package operandos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperandosService_Add_FullMethodName = "/OperandosService/Add"
)

// OperandosServiceClient is the client API for OperandosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperandosServiceClient interface {
	Add(ctx context.Context, in *Operandos, opts ...grpc.CallOption) (*OperandosResultado, error)
}

type operandosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperandosServiceClient(cc grpc.ClientConnInterface) OperandosServiceClient {
	return &operandosServiceClient{cc}
}

func (c *operandosServiceClient) Add(ctx context.Context, in *Operandos, opts ...grpc.CallOption) (*OperandosResultado, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperandosResultado)
	err := c.cc.Invoke(ctx, OperandosService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperandosServiceServer is the server API for OperandosService service.
// All implementations must embed UnimplementedOperandosServiceServer
// for forward compatibility.
type OperandosServiceServer interface {
	Add(context.Context, *Operandos) (*OperandosResultado, error)
	mustEmbedUnimplementedOperandosServiceServer()
}

// UnimplementedOperandosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperandosServiceServer struct{}

func (UnimplementedOperandosServiceServer) Add(context.Context, *Operandos) (*OperandosResultado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedOperandosServiceServer) mustEmbedUnimplementedOperandosServiceServer() {}
func (UnimplementedOperandosServiceServer) testEmbeddedByValue()                          {}

// UnsafeOperandosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperandosServiceServer will
// result in compilation errors.
type UnsafeOperandosServiceServer interface {
	mustEmbedUnimplementedOperandosServiceServer()
}

func RegisterOperandosServiceServer(s grpc.ServiceRegistrar, srv OperandosServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperandosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperandosService_ServiceDesc, srv)
}

func _OperandosService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operandos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperandosServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperandosService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperandosServiceServer).Add(ctx, req.(*Operandos))
	}
	return interceptor(ctx, in, info, handler)
}

// OperandosService_ServiceDesc is the grpc.ServiceDesc for OperandosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperandosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OperandosService",
	HandlerType: (*OperandosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _OperandosService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/operandos/operandos.proto",
}
